function x = meshgen_x(p)

switch p.xmesh_type
% Linearly spaced
case 1

    x = linspace(0,p.xmax,p.parr(1)+p.parr(2)+p.parr(3));

% Linearly spaced, more points at interfaces   
case 2
   
    x = [linspace(0, p.dcum(1)-p.dscr, p.parr(1)),...
        linspace(p.dcum(1)-p.dscr+p.deltax, p.dcum(1), p.pscr),...
        linspace(p.dcum(1)+p.deltax, p.dcum(1)+p.dscr, p.pscr),...
        linspace(p.dcum(1)+p.dscr+p.deltax, p.dcum(2)-p.dscr-p.deltax, p.parr(2)),...
        linspace(p.dcum(2)-p.dscr, p.dcum(2)-p.deltax, p.pscr),...
        linspace(p.dcum(2), p.dcum(2)+p.dscr-p.deltax, p.pscr),...
        linspace(p.dcum(2)+p.dscr, p.xmax, p.parr(3))];
        
% Linearly spaced, more points at interfaces   
case 3
   
    x = [linspace(0, p.dcum(1)-p.dscr, p.parr(1)),...
        linspace(p.dcum(1)-p.dscr+(p.dscr/p.pscr), p.dcum(1)-p.dint, p.pscr),...
        linspace(p.dcum(1)-p.dint+(p.dint/p.pint), p.dcum(1), p.pint),...
        linspace(p.dcum(1)+(p.dint/p.pint), p.dcum(1)+p.dint, p.pint),...
        linspace(p.dcum(1)+p.dint+(p.dint/p.pint), p.dcum(1)+p.dscr, p.pscr),...
        linspace(p.dcum(1)+p.dscr+(p.dscr/p.pscr), p.dcum(2)-p.dscr-(p.dscr/p.pscr), p.parr(2)),...
        linspace(p.dcum(2)-p.dscr, p.dcum(2)-p.dint-(p.dint/p.pint), p.pscr),...
        linspace(p.dcum(2)-p.dint, p.dcum(2)-(p.dint/p.pint), p.pint),...
        linspace(p.dcum(2), p.dcum(2)+p.dint-(p.dint/p.pint), p.pint),...
        linspace(p.dcum(2)+p.dint, p.dcum(2)+p.dscr-(p.dscr/p.pscr), p.pscr),...
        linspace(p.dcum(2)+p.dscr, p.xmax, p.parr(3));];
        
% Linearly spaced, more points at interfaces and electrodes
case 4
   
    x = [linspace(0, p.te, p.pepe),...
        linspace(p.te+p.deltax, p.dcum(1)-p.dscr, p.parr(1)),...
        linspace(p.dcum(1)-p.dscr+p.deltax, p.dcum(1), p.pscr),...
        linspace(p.dcum(1)+p.deltax, p.dcum(1)+p.dscr, p.pscr),...
        linspace(p.dcum(1)+p.dscr+p.deltax, p.dcum(2)-p.dscr-p.deltax, p.parr(2)),...
        linspace(p.dcum(2)-p.dscr, p.dcum(2)-p.deltax, p.pscr),...
        linspace(p.dcum(2), p.dcum(2)+p.dscr-p.deltax, p.pscr),...
        linspace(p.dcum(2)+p.dscr, p.xmax-p.te-p.deltax, p.parr(3)),...
        linspace(p.xmax-p.te, p.xmax, p.pepe);]; 

% Linearly spaced, more points at interfaces includes low Er n-type material (electrode)    
case 5
   
    x = [linspace(0, p.telp, p.pelp),...
        linspace(p.telp+(p.dscr/p.pscr), p.telp+p.dcum(1)-p.dscr, p.parr(1)),...
        linspace(p.telp+p.dcum(1)-p.dscr+(p.dscr/p.pscr), p.telp+p.dcum(1)-p.dint, p.pscr),...
        linspace(p.telp+p.dcum(1)-p.dint+(p.dint/p.pint), p.telp+p.dcum(1), p.pint),...
        linspace(p.telp+p.dcum(1)+(p.dint/p.pint), p.telp+p.dcum(1)+p.dint, p.pint),...
        linspace(p.telp+p.dcum(1)+p.dint+(p.dint/p.pint), p.telp+p.dcum(1)+p.dscr, p.pscr),...
        linspace(p.telp+p.dcum(1)+p.dscr+(p.dscr/p.pscr), p.telp+p.dcum(2)-p.dscr-(p.dscr/p.pscr), p.parr(2)),...
        linspace(p.telp+p.dcum(2)-p.dscr, p.telp+p.dcum(2)-p.dint-(p.dint/p.pint), p.pscr),...
        linspace(p.telp+p.dcum(2)-p.dint, p.telp+p.dcum(2)-(p.dint/p.pint), p.pint),...
        linspace(p.telp+p.dcum(2), p.telp+p.dcum(2)+p.dint-(p.dint/p.pint), p.pint),...
        linspace(p.telp+p.dcum(2)+p.dint, p.telp+p.dcum(2)+p.dscr-(p.dscr/p.pscr), p.pscr),...
        linspace(p.telp+p.dcum(2)+p.dscr, p.xmax-p.teln, p.parr(3)),...
        linspace(p.xmax-p.teln+(p.teln/p.peln), p.xmax, p.peln);];
           
case 7
   
    x = [linspace(0, p.telp-p.tjn, p.pelp),...
        linspace(p.telp-p.tjn+(p.tjn/p.pjn), p.telp+p.tjn-(p.tjn/p.pjn), p.pjn),...
        linspace(p.telp+p.tjn, p.telp+p.dcum(1)-p.dscr, p.parr(1)),...
        linspace(p.telp+p.dcum(1)-p.dscr+(p.dscr/p.pscr), p.telp+p.dcum(1)-p.dint, p.pscr),...
        linspace(p.telp+p.dcum(1)-p.dint+(p.dint/p.pint), p.telp+p.dcum(1), p.pint),...
        linspace(p.telp+p.dcum(1)+(p.dint/p.pint), p.telp+p.dcum(1)+p.dint, p.pint),...
        linspace(p.telp+p.dcum(1)+p.dint+(p.dint/p.pint), p.telp+p.dcum(1)+p.dscr, p.pscr),...
        linspace(p.telp+p.dcum(1)+p.dscr+(p.dscr/p.pscr), p.telp+p.dcum(1)+ti-p.dscr-(p.dscr/p.pscr), p.parr(2)),...
        linspace(p.telp+p.dcum(2)-p.dscr, p.telp+p.dcum(2)-p.dint-(p.dint/p.pint), p.pscr),...
        linspace(p.telp+p.dcum(2)-p.dint, p.telp+p.dcum(2)-(p.dint/p.pint), p.pint),...
        linspace(p.telp+p.dcum(2), p.telp+p.dcum(2)+p.dint-(p.dint/p.pint), p.pint),...
        linspace(p.telp+p.dcum(2)+p.dint, p.telp+p.dcum(2)+p.dscr-(p.dscr/p.pscr), p.pscr),...
        linspace(p.telp+p.dcum(2)+p.dscr, p.xmax-(p.teln+p.tjn), p.parr(3)),...
        linspace(p.xmax-(p.teln+p.tjn-(p.tjn/p.pjn)), p.xmax-(p.teln-p.tjn+(p.tjn/p.pjn)), p.pjn),...
        linspace(p.xmax-(p.teln-p.tjn), p.xmax, p.peln);];

    % Log 10 mesh - fails for high number of spatial points
    case 8
        
        halfmesh = logspace(log10(p.dmin), log10(p.d(2)/2+p.dmin), p.parr(2)/2);
        findmin = min(halfmesh);
        endspace = halfmesh(end) - halfmesh(end-1);
                
        x1 = [p.dcum(1) - p.dint - logspace(log10(p.dcum(1) - p.dint-p.dmin), log10(p.dmin), p.parr(1)),...
            linspace(p.dcum(1) - p.dint, p.dcum(1) + p.dint-p.dmin, p.pint),...
            p.dcum(1) + p.dint + logspace(log10(p.dmin), log10(p.d(2)/2+p.dmin-0.5*endspace), p.parr(2)/2)-p.dmin];         
    
        x2 = (p.xmax-fliplr(x1));
        
        x = [x1, x2];
            
    case 9
        
        halfmesh = p.dcum(1) - logspace(log10(p.dcum(1)+p.dmin), log10(p.dmin), p.parr(2)/2);
        findmin = min(halfmesh);
        endspace = halfmesh(end) - halfmesh(end-1);
                
        x = [p.dcum(1) + p.dmin - logspace(log10(p.d(1)), log10(p.dmin+endspace), p.parr(1)),...
              p.dcum(1) + logspace(log10(p.dmin), log10(p.d(2)/2+p.dmin-endspace), p.parr(2)/2)-p.dmin,...
              p.dcum(2) - logspace(log10(p.d(2)/2+p.dmin-endspace), log10(p.dmin), p.parr(2)/2)+p.dmin,...
              p.dcum(2) - p.dmin + logspace(log10(p.dmin+endspace), log10(p.d(3)), p.parr(3))];
        %x2 = (p.xmax-fliplr(x1));
        
        %x = [x1, x2];

        % Linearly spaced, more points at interfaces   
case 10
   
    x = [linspace(0, p.dcum(1)-p.dscr, p.parr(1)),...
        linspace(p.dcum(1)-p.dscr+(p.dscr/p.pscr), p.dcum(1), p.pscr),...     
        linspace(p.dcum(1)+(p.dint/p.pint), p.dcum(1)+2*p.dint, 2*p.pint),...
        linspace(p.dcum(1)+2*p.dint+(p.dint/p.pint), p.dcum(1)+p.dscr, p.pscr),...
        linspace(p.dcum(1)+p.dscr+(p.dscr/p.pscr), p.dcum(2)-p.dscr-(p.dscr/p.pscr), p.parr(2)),...
        linspace(p.dcum(2)-p.dscr, p.dcum(2)-2*p.dint-(p.dint/p.pint), p.pscr),...
        linspace(p.dcum(2)-2*p.dint, p.dcum(2)-(p.dint/p.pint), 2*p.pint),...
        linspace(p.dcum(2), p.dcum(2)+p.dscr-(p.dscr/p.pscr), p.pscr),...
        linspace(p.dcum(2)+p.dscr, p.xmax, p.parr(3));];        
        
    otherwise
        error('DrIFtFUSION:xmesh_type', [mfilename ' - xmesh_type not recognized'])
                
end 

px = length(x);

if p.meshx_figon == 1
    
    parr = 1:1:px;
    dpdx = gradient(parr, x);
    xmir = x;
    pxmir = 1:1:length(x);
    
    figure(1010);
    plot(xmir, pxmir,'.')
    xlabel('Position');
    ylabel('Point');
    
    
    figure(1011)
    plot(xmir, dpdx);
    xlabel('Position');
    ylabel('dpdx');    
    %ylim([-10,10])
     
    drawnow
end

end