function x = meshgen_x(p)

switch p.xmesh_type
% Linearly spaced
case 1

    x = linspace(0,p.xmax,p.pp+p.pii+p.pn);

% Linearly spaced, more points at interfaces   
case 2
   
    x = [linspace(0, p.tp-p.tscr, p.pp),...
        linspace(p.tp-p.tscr+p.deltax, p.tp, p.pscr),...
        linspace(p.tp+p.deltax, p.tp+p.tscr, p.pscr),...
        linspace(p.tp+p.tscr+p.deltax, p.tp+p.ti-p.tscr-p.deltax, p.pii),...
        linspace(p.tp+p.ti-p.tscr, p.tp+p.ti-p.deltax, p.pscr),...
        linspace(p.tp+p.ti, p.tp+p.ti+p.tscr-p.deltax, p.pscr),...
        linspace(p.tp+p.ti+p.tscr, p.xmax, p.pn)];
        
% Linearly spaced, more points at interfaces   
case 3
   
    x = [linspace(0, p.tp-p.tscr, p.pp),...
        linspace(p.tp-p.tscr+(p.tscr/p.pscr), p.tp-p.tint, p.pscr),...
        linspace(p.tp-p.tint+(p.tint/p.pint), p.tp, p.pint),...
        linspace(p.tp+(p.tint/p.pint), p.tp+p.tint, p.pint),...
        linspace(p.tp+p.tint+(p.tint/p.pint), p.tp+p.tscr, p.pscr),...
        linspace(p.tp+p.tscr+(p.tscr/p.pscr), p.tp+p.ti-p.tscr-(p.tscr/p.pscr), p.pii),...
        linspace(p.tp+p.ti-p.tscr, p.tp+p.ti-p.tint-(p.tint/p.pint), p.pscr),...
        linspace(p.tp+p.ti-p.tint, p.tp+p.ti-(p.tint/p.pint), p.pint),...
        linspace(p.tp+p.ti, p.tp+p.ti+p.tint-(p.tint/p.pint), p.pint),...
        linspace(p.tp+p.ti+p.tint, p.tp+p.ti+p.tscr-(p.tscr/p.pscr), p.pscr),...
        linspace(p.tp+p.ti+p.tscr, p.xmax, p.pn);];
        
% Linearly spaced, more points at interfaces and electrodes
case 4
   
    x = [linspace(0, p.te, p.pepe),...
        linspace(p.te+p.deltax, p.tp-p.tscr, p.pp),...
        linspace(p.tp-p.tscr+p.deltax, p.tp, p.pscr),...
        linspace(p.tp+p.deltax, p.tp+p.tscr, p.pscr),...
        linspace(p.tp+p.tscr+p.deltax, p.tp+p.ti-p.tscr-p.deltax, p.pii),...
        linspace(p.tp+p.ti-p.tscr, p.tp+p.ti-p.deltax, p.pscr),...
        linspace(p.tp+p.ti, p.tp+p.ti+p.tscr-p.deltax, p.pscr),...
        linspace(p.tp+p.ti+p.tscr, p.xmax-p.te-p.deltax, p.pn),...
        linspace(p.xmax-p.te, p.xmax, p.pepe);]; 

% Linearly spaced, more points at interfaces includes low Er n-type material (electrode)    
case 5
   
    x = [linspace(0, p.telp, p.pelp),...
        linspace(p.telp+(p.tscr/p.pscr), p.telp+p.tp-p.tscr, p.pp),...
        linspace(p.telp+p.tp-p.tscr+(p.tscr/p.pscr), p.telp+p.tp-p.tint, p.pscr),...
        linspace(p.telp+p.tp-p.tint+(p.tint/p.pint), p.telp+p.tp, p.pint),...
        linspace(p.telp+p.tp+(p.tint/p.pint), p.telp+p.tp+p.tint, p.pint),...
        linspace(p.telp+p.tp+p.tint+(p.tint/p.pint), p.telp+p.tp+p.tscr, p.pscr),...
        linspace(p.telp+p.tp+p.tscr+(p.tscr/p.pscr), p.telp+p.tp+p.ti-p.tscr-(p.tscr/p.pscr), p.pii),...
        linspace(p.telp+p.tp+p.ti-p.tscr, p.telp+p.tp+p.ti-p.tint-(p.tint/p.pint), p.pscr),...
        linspace(p.telp+p.tp+p.ti-p.tint, p.telp+p.tp+p.ti-(p.tint/p.pint), p.pint),...
        linspace(p.telp+p.tp+p.ti, p.telp+p.tp+p.ti+p.tint-(p.tint/p.pint), p.pint),...
        linspace(p.telp+p.tp+p.ti+p.tint, p.telp+p.tp+p.ti+p.tscr-(p.tscr/p.pscr), p.pscr),...
        linspace(p.telp+p.tp+p.ti+p.tscr, p.xmax-p.teln, p.pn),...
        linspace(p.xmax-p.teln+(p.teln/p.peln), p.xmax, p.peln);];
           
case 7
   
    x = [linspace(0, p.telp-p.tjn, p.pelp),...
        linspace(p.telp-p.tjn+(p.tjn/p.pjn), p.telp+p.tjn-(p.tjn/p.pjn), p.pjn),...
        linspace(p.telp+p.tjn, p.telp+p.tp-p.tscr, p.pp),...
        linspace(p.telp+p.tp-p.tscr+(p.tscr/p.pscr), p.telp+p.tp-p.tint, p.pscr),...
        linspace(p.telp+p.tp-p.tint+(p.tint/p.pint), p.telp+p.tp, p.pint),...
        linspace(p.telp+p.tp+(p.tint/p.pint), p.telp+p.tp+p.tint, p.pint),...
        linspace(p.telp+p.tp+p.tint+(p.tint/p.pint), p.telp+p.tp+p.tscr, p.pscr),...
        linspace(p.telp+p.tp+p.tscr+(p.tscr/p.pscr), p.telp+p.tp+ti-p.tscr-(p.tscr/p.pscr), p.pii),...
        linspace(p.telp+p.tp+p.ti-p.tscr, p.telp+p.tp+p.ti-p.tint-(p.tint/p.pint), p.pscr),...
        linspace(p.telp+p.tp+p.ti-p.tint, p.telp+p.tp+p.ti-(p.tint/p.pint), p.pint),...
        linspace(p.telp+p.tp+p.ti, p.telp+p.tp+p.ti+p.tint-(p.tint/p.pint), p.pint),...
        linspace(p.telp+p.tp+p.ti+p.tint, p.telp+p.tp+p.ti+p.tscr-(p.tscr/p.pscr), p.pscr),...
        linspace(p.telp+p.tp+p.ti+p.tscr, p.xmax-(p.teln+p.tjn), p.pn),...
        linspace(p.xmax-(p.teln+p.tjn-(p.tjn/p.pjn)), p.xmax-(p.teln-p.tjn+(p.tjn/p.pjn)), p.pjn),...
        linspace(p.xmax-(p.teln-p.tjn), p.xmax, p.peln);];

    % Log 10 mesh - fails for high number of spatial points
    case 8
        
        halfmesh = logspace(log10(p.tmin), log10(p.ti/2+p.tmin), p.pii/2);
        findmin = min(halfmesh);
        endspace = halfmesh(end) - halfmesh(end-1);
                
        x1 = [p.tp - p.tint - logspace(log10(p.tp - p.tint-p.tmin), log10(p.tmin), p.pp),...
            linspace(p.tp - p.tint, p.tp + p.tint-p.tmin, p.pint),...
            p.tp + p.tint + logspace(log10(p.tmin), log10(p.ti/2+p.tmin-0.5*endspace), p.pii/2)-p.tmin];         
    
        x2 = (p.xmax-fliplr(x1));
        
        x = [x1, x2];
            
    case 9
        
        halfmesh = p.tp - logspace(log10(p.tp+p.tmin), log10(p.tmin), p.pii/2);
        findmin = min(halfmesh);
        endspace = halfmesh(end) - halfmesh(end-1);
                
        x1 = [p.tp + p.tmin - logspace(log10(p.tp), log10(p.tmin), p.pp),...
              p.tp + logspace(log10(p.tmin), log10(p.ti/2+p.tmin-endspace), p.pii/2)-p.tmin + 1e-9];
    
        x2 = (p.xmax-fliplr(x1));
        
        x = [x1, x2];
               
    otherwise
        error('DrIFtFUSION:xmesh_type', [mfilename ' - xmesh_type not recognized'])
                
end 

px = length(x);

if p.meshx_figon == 1
    
    parr = 1:1:px;
    dpdx = gradient(parr, x);
    xmir = x;
    pxmir = 1:1:length(x);
    
    figure(1010);
    plot(xmir, pxmir,'.')
    xlabel('Position');
    ylabel('Point');
    
    
    figure(1011)
    plot(xmir, dpdx);
    xlabel('Position');
    ylabel('dpdx');    
    %ylim([-10,10])
     
    drawnow
end

end